name: "Merge pull requests (automerge-action) supports fast forward"
description: "Automatically merge pull requests that are ready"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "git-pull-request"
  color: "blue"
